// <auto-generated />
namespace Datalayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_adminlogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_adminlogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202404280955467_add_adminlogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
